# Generated by Django 5.0 on 2023-12-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='iiii', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
